[0.65.1] Migrate packages (#172)
* Update packages

* Upgrade RN project to 0.65.1

* Upgrade ios project to RN 0.65.1

* Fix tests

* Fix ios build error & support dooboo-ui with patch-packages (#173)

* Update snapshots

* Remove `jsxBracketSameLine` prettier config for deprecation

Co-authored-by: Dean <ydhun93@gmail.com>

diff --git a/patches/react-native+0.65.1.patch b/patches/react-native+0.65.1.patch
--- a/patches/react-native+0.65.1.patch
+++ b/patches/react-native+0.65.1.patch
@@ -6,10 +6,10 @@ index 0000000..361f5fb
 @@ -0,0 +1 @@
 +export RCT_METRO_PORT=8081
 diff --git a/node_modules/react-native/scripts/generate-specs.sh b/node_modules/react-native/scripts/generate-specs.sh
-index aed955e..7162eb3 100755
+index b66f4c9..f073fd9 100755
 --- a/node_modules/react-native/scripts/generate-specs.sh
 +++ b/node_modules/react-native/scripts/generate-specs.sh
-@@ -1,91 +1,91 @@
+@@ -1,101 +1,101 @@
 -#!/bin/bash
 -# Copyright (c) Facebook, Inc. and its affiliates.
 -#
@@ -22,14 +22,14 @@ index aed955e..7162eb3 100755
 -#
 -# Optionally, set these envvars to override defaults:
 -# - SRCS_DIR: Path to JavaScript sources
--# - CODEGEN_MODULES_LIBRARY_NAME: Defaults to FBReactNativeSpec
--# - CODEGEN_MODULES_OUTPUT_DIR: Defaults to React/$CODEGEN_MODULES_LIBRARY_NAME/$CODEGEN_MODULES_LIBRARY_NAME
--# - CODEGEN_COMPONENTS_LIBRARY_NAME: Defaults to rncore
--# - CODEGEN_COMPONENTS_OUTPUT_DIR: Defaults to ReactCommon/react/renderer/components/$CODEGEN_COMPONENTS_LIBRARY_NAME
+-# - MODULES_LIBRARY_NAME: Defaults to FBReactNativeSpec
+-# - MODULES_OUTPUT_DIR: Defaults to React/$MODULES_LIBRARY_NAME/$MODULES_LIBRARY_NAME
+-# - COMPONENTS_LIBRARY_NAME: Defaults to rncore
+-# - COMPONENTS_OUTPUT_DIR: Defaults to ReactCommon/react/renderer/components/$COMPONENTS_LIBRARY_NAME
 -#
 -# Usage:
 -#   ./scripts/generate-specs.sh
--#   SRCS_DIR=myapp/js CODEGEN_MODULES_LIBRARY_NAME=MySpecs CODEGEN_MODULES_OUTPUT_DIR=myapp/MySpecs ./scripts/generate-specs.sh
+-#   SRCS_DIR=myapp/js MODULES_LIBRARY_NAME=MySpecs MODULES_OUTPUT_DIR=myapp/MySpecs ./scripts/generate-specs.sh
 -#
 -
 -# shellcheck disable=SC2038
@@ -39,12 +39,13 @@ index aed955e..7162eb3 100755
 -THIS_DIR=$(cd -P "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)
 -TEMP_DIR=$(mktemp -d /tmp/react-native-codegen-XXXXXXXX)
 -RN_DIR=$(cd "$THIS_DIR/.." && pwd)
+-USE_FABRIC="${USE_FABRIC:-0}"
 -
--# find node path
+-# Find path to Node
+-# shellcheck source=/dev/null
 -source "$RN_DIR/scripts/find-node.sh"
 -
 -NODE_BINARY="${NODE_BINARY:-$(command -v node || true)}"
--USE_FABRIC="${USE_FABRIC:-0}"
 -
 -cleanup () {
 -  set +e
@@ -58,25 +59,34 @@ index aed955e..7162eb3 100755
 -
 -main() {
 -  SRCS_DIR=${SRCS_DIR:-$(cd "$RN_DIR/Libraries" && pwd)}
--  CODEGEN_MODULES_LIBRARY_NAME=${CODEGEN_MODULES_LIBRARY_NAME:-FBReactNativeSpec}
+-  MODULES_LIBRARY_NAME=${MODULES_LIBRARY_NAME:-FBReactNativeSpec}
 -
--  CODEGEN_COMPONENTS_LIBRARY_NAME=${CODEGEN_COMPONENTS_LIBRARY_NAME:-rncore}
--  CODEGEN_MODULES_OUTPUT_DIR=${CODEGEN_MODULES_OUTPUT_DIR:-"$RN_DIR/React/$CODEGEN_MODULES_LIBRARY_NAME/$CODEGEN_MODULES_LIBRARY_NAME"}
--  # TODO: $CODEGEN_COMPONENTS_PATH should be programmatically specified, and may change with use_frameworks! support.
--  CODEGEN_COMPONENTS_PATH="ReactCommon/react/renderer/components"
--  CODEGEN_COMPONENTS_OUTPUT_DIR=${CODEGEN_COMPONENTS_OUTPUT_DIR:-"$RN_DIR/$CODEGEN_COMPONENTS_PATH/$CODEGEN_COMPONENTS_LIBRARY_NAME"}
+-  COMPONENTS_LIBRARY_NAME=${COMPONENTS_LIBRARY_NAME:-rncore}
+-  MODULES_OUTPUT_DIR=${MODULES_OUTPUT_DIR:-"$RN_DIR/React/$MODULES_LIBRARY_NAME/$MODULES_LIBRARY_NAME"}
+-  # TODO: $COMPONENTS_PATH should be programmatically specified, and may change with use_frameworks! support.
+-  COMPONENTS_PATH="ReactCommon/react/renderer/components"
+-  COMPONENTS_OUTPUT_DIR=${COMPONENTS_OUTPUT_DIR:-"$RN_DIR/$COMPONENTS_PATH/$COMPONENTS_LIBRARY_NAME"}
 -
 -  TEMP_OUTPUT_DIR="$TEMP_DIR/out"
 -  SCHEMA_FILE="$TEMP_DIR/schema.json"
+-
+-  CODEGEN_REPO_PATH="$RN_DIR/packages/react-native-codegen"
+-  CODEGEN_NPM_PATH="$RN_DIR/../react-native-codegen"
 -
 -  if [ -z "$NODE_BINARY" ]; then
 -    echo "Error: Could not find node. Make sure it is in bash PATH or set the NODE_BINARY environment variable." 1>&2
 -    exit 1
 -  fi
 -
--  CODEGEN_PATH=$("$NODE_BINARY" -e "console.log(require('path').dirname(require.resolve('react-native-codegen/package.json')))")
+-  if [ -d "$CODEGEN_REPO_PATH" ]; then
+-    CODEGEN_PATH=$(cd "$CODEGEN_REPO_PATH" && pwd)
+-  elif [ -d "$CODEGEN_NPM_PATH" ]; then
+-    CODEGEN_PATH=$(cd "$CODEGEN_NPM_PATH" && pwd)
+-  else
+-    echo "Error: Could not determine react-native-codegen location. Try running 'yarn install' or 'npm install' in your project root." 1>&2
+-    exit 1
+-  fi
 -
--  # Special case for running CodeGen from source: build it
 -  if [ ! -d "$CODEGEN_PATH/lib" ]; then
 -    describe "Building react-native-codegen package"
 -    bash "$CODEGEN_PATH/scripts/oss/build.sh"
@@ -87,14 +97,14 @@ index aed955e..7162eb3 100755
 -
 -  describe "Generating native code from schema (iOS)"
 -  pushd "$RN_DIR" >/dev/null || exit 1
--    "$NODE_BINARY" scripts/generate-specs-cli.js ios "$SCHEMA_FILE" "$TEMP_OUTPUT_DIR" "$CODEGEN_MODULES_LIBRARY_NAME"
+-    "$NODE_BINARY" scripts/generate-specs-cli.js ios "$SCHEMA_FILE" "$TEMP_OUTPUT_DIR" "$MODULES_LIBRARY_NAME"
 -  popd >/dev/null || exit 1
 -
 -  describe "Copying output to final directory"
--  mkdir -p "$CODEGEN_COMPONENTS_OUTPUT_DIR" "$CODEGEN_MODULES_OUTPUT_DIR"
--  cp -R "$TEMP_OUTPUT_DIR/$CODEGEN_MODULES_LIBRARY_NAME.h" "$TEMP_OUTPUT_DIR/$CODEGEN_MODULES_LIBRARY_NAME-generated.mm" "$CODEGEN_MODULES_OUTPUT_DIR" || exit 1
--  find "$TEMP_OUTPUT_DIR" -type f | xargs sed -i.bak "s/$CODEGEN_MODULES_LIBRARY_NAME/$CODEGEN_COMPONENTS_LIBRARY_NAME/g" || exit 1
--  find "$TEMP_OUTPUT_DIR" -type f -not -iname "$CODEGEN_MODULES_LIBRARY_NAME*" -exec cp '{}' "$CODEGEN_COMPONENTS_OUTPUT_DIR/" ';' || exit 1
+-  mkdir -p "$COMPONENTS_OUTPUT_DIR" "$MODULES_OUTPUT_DIR"
+-  cp -R "$TEMP_OUTPUT_DIR/$MODULES_LIBRARY_NAME.h" "$TEMP_OUTPUT_DIR/$MODULES_LIBRARY_NAME-generated.mm" "$MODULES_OUTPUT_DIR" || exit 1
+-  find "$TEMP_OUTPUT_DIR" -type f | xargs sed -i.bak "s/$MODULES_LIBRARY_NAME/$COMPONENTS_LIBRARY_NAME/g" || exit 1
+-  find "$TEMP_OUTPUT_DIR" -type f -not -iname "$MODULES_LIBRARY_NAME*" -exec cp '{}' "$COMPONENTS_OUTPUT_DIR/" ';' || exit 1
 -
 -  echo >&2 'Done.'
 -}
@@ -113,14 +123,14 @@ index aed955e..7162eb3 100755
 +# #
 +# # Optionally, set these envvars to override defaults:
 +# # - SRCS_DIR: Path to JavaScript sources
-+# # - CODEGEN_MODULES_LIBRARY_NAME: Defaults to FBReactNativeSpec
-+# # - CODEGEN_MODULES_OUTPUT_DIR: Defaults to React/$CODEGEN_MODULES_LIBRARY_NAME/$CODEGEN_MODULES_LIBRARY_NAME
-+# # - CODEGEN_COMPONENTS_LIBRARY_NAME: Defaults to rncore
-+# # - CODEGEN_COMPONENTS_OUTPUT_DIR: Defaults to ReactCommon/react/renderer/components/$CODEGEN_COMPONENTS_LIBRARY_NAME
++# # - MODULES_LIBRARY_NAME: Defaults to FBReactNativeSpec
++# # - MODULES_OUTPUT_DIR: Defaults to React/$MODULES_LIBRARY_NAME/$MODULES_LIBRARY_NAME
++# # - COMPONENTS_LIBRARY_NAME: Defaults to rncore
++# # - COMPONENTS_OUTPUT_DIR: Defaults to ReactCommon/react/renderer/components/$COMPONENTS_LIBRARY_NAME
 +# #
 +# # Usage:
 +# #   ./scripts/generate-specs.sh
-+# #   SRCS_DIR=myapp/js CODEGEN_MODULES_LIBRARY_NAME=MySpecs CODEGEN_MODULES_OUTPUT_DIR=myapp/MySpecs ./scripts/generate-specs.sh
++# #   SRCS_DIR=myapp/js MODULES_LIBRARY_NAME=MySpecs MODULES_OUTPUT_DIR=myapp/MySpecs ./scripts/generate-specs.sh
 +# #
 +
 +# # shellcheck disable=SC2038
@@ -130,12 +140,13 @@ index aed955e..7162eb3 100755
 +# THIS_DIR=$(cd -P "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)
 +# TEMP_DIR=$(mktemp -d /tmp/react-native-codegen-XXXXXXXX)
 +# RN_DIR=$(cd "$THIS_DIR/.." && pwd)
++# USE_FABRIC="${USE_FABRIC:-0}"
 +
-+# # find node path
++# # Find path to Node
++# # shellcheck source=/dev/null
 +# source "$RN_DIR/scripts/find-node.sh"
 +
 +# NODE_BINARY="${NODE_BINARY:-$(command -v node || true)}"
-+# USE_FABRIC="${USE_FABRIC:-0}"
 +
 +# cleanup () {
 +#   set +e
@@ -149,25 +160,34 @@ index aed955e..7162eb3 100755
 +
 +# main() {
 +#   SRCS_DIR=${SRCS_DIR:-$(cd "$RN_DIR/Libraries" && pwd)}
-+#   CODEGEN_MODULES_LIBRARY_NAME=${CODEGEN_MODULES_LIBRARY_NAME:-FBReactNativeSpec}
++#   MODULES_LIBRARY_NAME=${MODULES_LIBRARY_NAME:-FBReactNativeSpec}
 +
-+#   CODEGEN_COMPONENTS_LIBRARY_NAME=${CODEGEN_COMPONENTS_LIBRARY_NAME:-rncore}
-+#   CODEGEN_MODULES_OUTPUT_DIR=${CODEGEN_MODULES_OUTPUT_DIR:-"$RN_DIR/React/$CODEGEN_MODULES_LIBRARY_NAME/$CODEGEN_MODULES_LIBRARY_NAME"}
-+#   # TODO: $CODEGEN_COMPONENTS_PATH should be programmatically specified, and may change with use_frameworks! support.
-+#   CODEGEN_COMPONENTS_PATH="ReactCommon/react/renderer/components"
-+#   CODEGEN_COMPONENTS_OUTPUT_DIR=${CODEGEN_COMPONENTS_OUTPUT_DIR:-"$RN_DIR/$CODEGEN_COMPONENTS_PATH/$CODEGEN_COMPONENTS_LIBRARY_NAME"}
++#   COMPONENTS_LIBRARY_NAME=${COMPONENTS_LIBRARY_NAME:-rncore}
++#   MODULES_OUTPUT_DIR=${MODULES_OUTPUT_DIR:-"$RN_DIR/React/$MODULES_LIBRARY_NAME/$MODULES_LIBRARY_NAME"}
++#   # TODO: $COMPONENTS_PATH should be programmatically specified, and may change with use_frameworks! support.
++#   COMPONENTS_PATH="ReactCommon/react/renderer/components"
++#   COMPONENTS_OUTPUT_DIR=${COMPONENTS_OUTPUT_DIR:-"$RN_DIR/$COMPONENTS_PATH/$COMPONENTS_LIBRARY_NAME"}
 +
 +#   TEMP_OUTPUT_DIR="$TEMP_DIR/out"
 +#   SCHEMA_FILE="$TEMP_DIR/schema.json"
++
++#   CODEGEN_REPO_PATH="$RN_DIR/packages/react-native-codegen"
++#   CODEGEN_NPM_PATH="$RN_DIR/../react-native-codegen"
 +
 +#   if [ -z "$NODE_BINARY" ]; then
 +#     echo "Error: Could not find node. Make sure it is in bash PATH or set the NODE_BINARY environment variable." 1>&2
 +#     exit 1
 +#   fi
 +
-+#   CODEGEN_PATH=$("$NODE_BINARY" -e "console.log(require('path').dirname(require.resolve('react-native-codegen/package.json')))")
++#   if [ -d "$CODEGEN_REPO_PATH" ]; then
++#     CODEGEN_PATH=$(cd "$CODEGEN_REPO_PATH" && pwd)
++#   elif [ -d "$CODEGEN_NPM_PATH" ]; then
++#     CODEGEN_PATH=$(cd "$CODEGEN_NPM_PATH" && pwd)
++#   else
++#     echo "Error: Could not determine react-native-codegen location. Try running 'yarn install' or 'npm install' in your project root." 1>&2
++#     exit 1
++#   fi
 +
-+#   # Special case for running CodeGen from source: build it
 +#   if [ ! -d "$CODEGEN_PATH/lib" ]; then
 +#     describe "Building react-native-codegen package"
 +#     bash "$CODEGEN_PATH/scripts/oss/build.sh"
@@ -178,14 +198,14 @@ index aed955e..7162eb3 100755
 +
 +#   describe "Generating native code from schema (iOS)"
 +#   pushd "$RN_DIR" >/dev/null || exit 1
-+#     "$NODE_BINARY" scripts/generate-specs-cli.js ios "$SCHEMA_FILE" "$TEMP_OUTPUT_DIR" "$CODEGEN_MODULES_LIBRARY_NAME"
++#     "$NODE_BINARY" scripts/generate-specs-cli.js ios "$SCHEMA_FILE" "$TEMP_OUTPUT_DIR" "$MODULES_LIBRARY_NAME"
 +#   popd >/dev/null || exit 1
 +
 +#   describe "Copying output to final directory"
-+#   mkdir -p "$CODEGEN_COMPONENTS_OUTPUT_DIR" "$CODEGEN_MODULES_OUTPUT_DIR"
-+#   cp -R "$TEMP_OUTPUT_DIR/$CODEGEN_MODULES_LIBRARY_NAME.h" "$TEMP_OUTPUT_DIR/$CODEGEN_MODULES_LIBRARY_NAME-generated.mm" "$CODEGEN_MODULES_OUTPUT_DIR" || exit 1
-+#   find "$TEMP_OUTPUT_DIR" -type f | xargs sed -i.bak "s/$CODEGEN_MODULES_LIBRARY_NAME/$CODEGEN_COMPONENTS_LIBRARY_NAME/g" || exit 1
-+#   find "$TEMP_OUTPUT_DIR" -type f -not -iname "$CODEGEN_MODULES_LIBRARY_NAME*" -exec cp '{}' "$CODEGEN_COMPONENTS_OUTPUT_DIR/" ';' || exit 1
++#   mkdir -p "$COMPONENTS_OUTPUT_DIR" "$MODULES_OUTPUT_DIR"
++#   cp -R "$TEMP_OUTPUT_DIR/$MODULES_LIBRARY_NAME.h" "$TEMP_OUTPUT_DIR/$MODULES_LIBRARY_NAME-generated.mm" "$MODULES_OUTPUT_DIR" || exit 1
++#   find "$TEMP_OUTPUT_DIR" -type f | xargs sed -i.bak "s/$MODULES_LIBRARY_NAME/$COMPONENTS_LIBRARY_NAME/g" || exit 1
++#   find "$TEMP_OUTPUT_DIR" -type f -not -iname "$MODULES_LIBRARY_NAME*" -exec cp '{}' "$COMPONENTS_OUTPUT_DIR/" ';' || exit 1
 +
 +#   echo >&2 'Done.'
 +# }
